package uz.mediasolutions.siryo24bot.enums;

public enum StepName {
    SHARE_PHONE_NUMBER,
    INCORRECT_PHONE_FORMAT,
    ENTER_NAME,
    CHOOSE_FROM_MENU,
    CHOOSE_ROLE, SEND_SUGG_COMP, MENU_SETTINGS, CHANGE_NAME, CHANGE_PHONE_NUMBER, CHANGE_LANGUAGE, INCORRECT_PHONE_FORMAT_1, CHANGE_ROLE, CHOOSE_LANG

}
